---
# GitHub Actions workflow for commits pushed to the Maud repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --console=plain --no-daemon --stacktrace
      - uses: actions/upload-artifact@v3
        with:
          name: linux build
          path: build/distributions/Maud.tar

  Java20-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 20
      - run: ./gradlew build --console=plain --no-daemon --stacktrace
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: windows build
          path: build/distributions/Maud.zip
